@echo off
setlocal EnableDelayedExpansion

REM ============================================================
REM setup_hook.bat
REM Install AiReviewer git pre-commit hook into the current repository.
REM
REM Usage:
REM   setup_hook.bat <path\to\aireviewr.exe>
REM
REM Example:
REM   setup_hook.bat "C:\Tools\aireviewr.exe"
REM
REM Run this script from the root of the target git repository.
REM ============================================================

REM --- Argument check ---
if "%~1"=="" (
    echo [ERROR] Specify the path to aireviewr.exe as the first argument.
    echo.
    echo Usage  : setup_hook.bat ^<path\to\aireviewr.exe^>
    echo Example: setup_hook.bat "C:\Tools\aireviewr.exe"
    exit /b 1
)

set "EXE_PATH=%~1"

REM --- Check exe exists ---
if not exist "%EXE_PATH%" (
    echo [ERROR] Executable not found: %EXE_PATH%
    exit /b 1
)

REM --- Check git repository ---
if not exist ".git" (
    echo [ERROR] No .git folder found in the current directory.
    echo Run this script from the root of a git repository.
    exit /b 1
)

REM --- Create hooks directory if missing ---
if not exist ".git\hooks" (
    mkdir ".git\hooks"
)

set "HOOK_PATH=.git\hooks\pre-commit"

REM --- Warn if hook already exists ---
if exist "%HOOK_PATH%" (
    echo [WARNING] A pre-commit hook already exists: %HOOK_PATH%
    set /p "OVERWRITE=Overwrite? [y/N]: "
    if /i not "!OVERWRITE!"=="y" (
        echo Installation cancelled.
        exit /b 0
    )
)

REM --- Write hook script with LF line endings and no BOM ---
REM Temporarily disable DelayedExpansion so "!" in "#!/bin/sh" is passed verbatim to PowerShell.
setlocal DisableDelayedExpansion
set "AIREVIEW_EXE_PATH=%EXE_PATH%"
set "AIREVIEW_HOOK_DEST=%CD%\%HOOK_PATH%"

powershell -NoProfile -Command "$exe=$env:AIREVIEW_EXE_PATH; $dest=$env:AIREVIEW_HOOK_DEST; $lf=[char]10; $dq=[char]34; $c='#!/bin/sh'+$lf+'# AiReviewer pre-commit hook'+$lf+'# Auto-generated by tools/setup_hook.bat'+$lf+$dq+$exe+$dq+$lf+'exit $?'+$lf; [System.IO.File]::WriteAllText($dest,$c,(New-Object System.Text.UTF8Encoding $false))"

set "PS_EXIT=%ERRORLEVEL%"
endlocal & set "PS_EXIT=%PS_EXIT%"

if "%PS_EXIT%" neq "0" (
    echo [ERROR] Failed to write hook script.
    exit /b 1
)

echo.
echo [OK] pre-commit hook installed successfully.
echo   Hook path  : %HOOK_PATH%
echo   Executable : %EXE_PATH%
echo.
echo AiReviewer will run automatically on the next commit.
echo To remove the hook, delete: %HOOK_PATH%

endlocal
exit /b 0